// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYherrdSRbByCp9ZyYiHW_3ypML5rRxE8',
    appId: '1:1035728732221:android:63df213e88622a9b07ea54',
    messagingSenderId: '1035728732221',
    projectId: 'quiz-app-3bfe4',
    storageBucket: 'quiz-app-3bfe4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS4QRYCv3tPdK8HfI2LAMlqIa36xedclw',
    appId: '1:1035728732221:ios:79509c52d20d632f07ea54',
    messagingSenderId: '1035728732221',
    projectId: 'quiz-app-3bfe4',
    storageBucket: 'quiz-app-3bfe4.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6iKvhyRFi8AIejIcr_lfGTe3c97odT68',
    appId: '1:1035728732221:web:bceb497e28a0320d07ea54',
    messagingSenderId: '1035728732221',
    projectId: 'quiz-app-3bfe4',
    authDomain: 'quiz-app-3bfe4.firebaseapp.com',
    storageBucket: 'quiz-app-3bfe4.firebasestorage.app',
    measurementId: 'G-XQBB35D82R',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS4QRYCv3tPdK8HfI2LAMlqIa36xedclw',
    appId: '1:1035728732221:ios:79509c52d20d632f07ea54',
    messagingSenderId: '1035728732221',
    projectId: 'quiz-app-3bfe4',
    storageBucket: 'quiz-app-3bfe4.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6iKvhyRFi8AIejIcr_lfGTe3c97odT68',
    appId: '1:1035728732221:web:1479e3f56d21cf2207ea54',
    messagingSenderId: '1035728732221',
    projectId: 'quiz-app-3bfe4',
    authDomain: 'quiz-app-3bfe4.firebaseapp.com',
    storageBucket: 'quiz-app-3bfe4.firebasestorage.app',
    measurementId: 'G-DGXW05HRRK',
  );

}